from unittest import TestCase


class TestExceptionCascade(TestCase):
    def test_validate(self):
        self.fail()
